feat: :sparkles: add clock module to check valid participation and run (#13)
fukaeridesui/suipstakes pull request #21
Opened 2024-09-06 04:57 UTC by fukaeridesui

2024-09-10 08:54 UTC, 0x-onigiri requested changes
2点コメントしました！

2024-09-10 08:54 UTC, 0x-onigiri commented on contracts/sources/raffle.move
> +    end_timestamp: u64,
assertで `start_timestamp < end_timestamp` チェック追加お願いします！

2024-09-10 08:54 UTC, 0x-onigiri commented on contracts/sources/raffle.move
> +    assert!(raffle.end_timestamp > clock.timestamp_ms(), ERaffleEnded);
それぞれ `<=` `>=` で良さそうに思いましたが意図的に `=` なしにしているのでしょうか？

2024-09-12 11:56 UTC, fukaeridesui commented on contracts/sources/raffle.move
> +    end_timestamp: u64,
イベント作成時(`create()`実行時)のみで十分と判断しそちらだけ追加しました！

2024-09-12 11:58 UTC, fukaeridesui commented on contracts/sources/raffle.move
> +    assert!(raffle.end_timestamp > clock.timestamp_ms(), ERaffleEnded);
〜よりあとと考えて`=`付けていなかったです！
が、よく考えたらご指摘のように「以降」と捉えるのが普通と思うので修正しました！

2024-09-12 12:26 UTC, fukaeridesui commented
コンフリクトの解消も併せて行いました
こちらについても問題ないかちらっとご確認いただけると助かります🙏

2024-09-12 13:45 UTC, 0x-onigiri commented on contracts/sources/raffle.move
> +    assert!(raffle.end_timestamp <= clock.timestamp_ms(), ERaffleNotEnded);
ここは `<` のままで問題ないかも？と思いました！

2024-09-12 13:45 UTC, 0x-onigiri commented
コンフリクト解消最高です😆

2024-09-13 00:50 UTC, fukaeridesui commented on contracts/sources/raffle.move
> +    assert!(raffle.end_timestamp <= clock.timestamp_ms(), ERaffleNotEnded);
おそらくおにぎりさんが正しい...
直しました！

2024-09-14 08:08 UTC, 0x-onigiri approved these changes
ありがとうございます！ LGTM~!!!!!

2024-09-21 12:22 UTC, merged